### ISSUE TITLE
:app:ndkBuild error

### ISSUE THREAD

**Issue by afonsohfontes** [Petroula/Android-Car-duino#8]
When executing the command _gradlew build_ on cmd I get the error bellow. Any idea of how can I fix this?

![image](https://user-images.githubusercontent.com/21039838/28509678-2b68bb92-701a-11e7-9d24-037661fdf552.png)

```
:app:ndkBuild
make: Entering directory `C:/Users/Afonso/Desktop/lane-following/Android-Car-duino-master/app/src/main'
jni/Android.mk:7: null/sdk/native/jni/OpenCV.mk: No such file or directory
jni/Android.mk:7: null/sdk/native/jni/OpenCV.mk: No such file or directory
make: Leaving directory `C:/Users/Afonso/Desktop/lane-following/Android-Car-duino-master/app/src/main'
make: *** No rule to make target `null/sdk/native/jni/OpenCV.mk'.  Stop.
:app:ndkBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:ndkBuild'.
Process 'command 'C:\Users\Afonso\Desktop\lane-following\android-ndk-r14b/ndk-build.cmd'' finished with non-zero exit value 2
```

**Comment by platisd** [comment]
> No rule to make target `**null**/sdk/native/jni/OpenCV.mk'.

Android Studio did not manage to properly set the path to the said .mk file, this has happened before, not sure why. Try to edit the culprit file (`Android-Car-duino/app/src/main/jni/Android.mk`) and replace `null` in the specific line with the correct path.

**Comment by afonsohfontes** [comment]
Hello @platisd, thanks for your answer! Your tip worked for that error but I ended up generating two others:
![image](https://user-images.githubusercontent.com/21039838/28534136-02d8fa6e-7076-11e7-8c2d-ac2d2ab8be66.png)


1st Error:
`:app:lint
Ran lint on variant debug: 87 issues found
Ran lint on variant release: 87 issues found
Wrote HTML report to file:///C:/Users/Afonso/Desktop/lane-following/Android-Car-duino-master/app/build/reports/lint-results.html
Wrote XML report to file:///C:/Users/Afonso/Desktop/lane-following/Android-Car-duino-master/app/build/reports/lint-results.xml` 

The first I was able to bypass by adding the lines bellow to app/build.dradle:
`    lintOptions {
        abortOnError false
    }
`

Any tips on the second error?
```
`test.AutodriveTest > initializationError FAILED
    java.lang.UnsatisfiedLinkError at AutodriveTest.java:13

1 test completed, 1 failed
:app:testDebugUnitTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:testDebugUnitTest'.
> There were failing tests. See the report at: file:///C:/Users/Afonso/Desktop/lane-following/Android-Car-duino-master/app/build/reports/tests/testDebugUnitTest/index.html`
```

The html file it created looks like:
![image](https://user-images.githubusercontent.com/21039838/28534518-58df97be-7077-11e7-9b08-8996506f15af.png)
```
`java.lang.UnsatisfiedLinkError: no gnustl_shared in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at test.AutodriveTest.<clinit>(AutodriveTest.java:13)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at junit.framework.TestSuite.createTest(TestSuite.java:60)
	at junit.framework.TestSuite.addTestMethod(TestSuite.java:307)
	at junit.framework.TestSuite.addTestsFromTestCase(TestSuite.java:150)
	at junit.framework.TestSuite.<init>(TestSuite.java:129)
	at org.junit.internal.runners.JUnit38ClassRunner.<init>(JUnit38ClassRunner.java:74)
	at org.junit.internal.builders.JUnit3Builder.runnerForClass(JUnit3Builder.java:11)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy3.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:377)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`
```

**Comment by platisd** [comment]
I just built the project successfully using a fresh install of Android Studio and Android whatsoever. :smiley: 
I am on Ubuntu 16.04 so I cannot completely reproduce your Windows setting (nor have I seen these errors before). As you might have guessed, development on this project has ceased (from our side at least) and therefore the build setup is rather outdated.

So I cloned and followed the instructions on [README](https://github.com/Petroula/Android-Car-duino/blob/master/README.md). It did not work right away, but after following Android Studio's prompts here and there to use some more recent versions of build tools it was eventually built. Moreover, I used [this](https://sourceforge.net/projects/opencvlibrary/files/opencv-android/3.0.0/OpenCV-3.0.0-android-sdk-1.zip/download) OpenCV.

I created a [branch](https://github.com/Petroula/Android-Car-duino/tree/update_settings) for you. Please try to use it and let me know if it does the trick for you as well, so I may merge it with master.

**Comment by afonsohfontes** [comment]
Thanks again for your time, @platisd! I really appreciate your help.
It is showing the same error when I use cmd on windows, but it now builds the apk using Android Studio. I successfully installed the universal release apk, but the app crashes and closes on start-up on my Samsung running 5.0.1. But I am now suspecting the problem sits on my phone. For the sake of testing, do you mind sharing the apk file you built?

**Comment by platisd** [comment]
I would strongly suggest trying to compile the project if you are interested in developing or reproducing it. After all, even if you do install the app on your phone, you won't get to see or do much, as it will need to pair with a bluetooth device (i.e. the car). Also do not forget to install OpenCV on your phone if you want the app to run.

Additionally, I have to strongly advise **against** downloading and installing apk's from untrusted sources, such as myself. :stuck_out_tongue: 
Anyway, I have uploaded the apk I just built [here](http://www.droidbin.com/p1blr85ekv1ckk30m1os418g7c103). However as I previously wrote, I do not see the use of installing it.

**Comment by afonsohfontes** [comment]
> Also do not forget to install OpenCV on your phone if you want the app to run.

This must be the reason why it crashes, then. How do I do it? Is it enough to install OpenCV Manager from appstore?

**Comment by platisd** [comment]
> Is it enough to install OpenCV Manager from appstore?

Yeap

**Comment by afonsohfontes** [comment]
It worked, thank you for your time and patience!

**Comment by platisd** [comment]
OK good. I am closing this issue but not merging the newly created branch until I receive notification from you that it worked. :+1:  (feel free to re-open the issue in case you still have problems compiling the project)
